name: Discord Automation

on:
  push:
    branches:
      - master

jobs:
  discord-webhook:
    runs-on: ubuntu-latest
    steps:
    - env:
        DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1352504716579573795/yfbhnbwFrmX1AXa9OQdKTVBWAhwm_X6DP0yJyziWPG7gQiGHEk3OsvRPyA51ZYZXJeCD"
        DISCORD_EMBEDS: '[{"title":"Meow!","color":1127128},{"title":"Meow-meow!","color":14177041}]'
      uses: Ilshidur/action-discord@0.3.2
      if: "${{ env.DISCORD_WEBHOOK != '' }}"
      with:
        args: "Message"
